name: CI Pipeline

on:
  push:
    branches: [ "feat/ci-cd-bootstrap" ]
  pull_request:
    branches: [ "feat/ci-cd-bootstrap" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      # Backend
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Build backend
        working-directory: ./backend
        run: |
          if [ -f package.json ]; then
            npm run build || echo "No build step for backend"
          fi

      # Frontend
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # ✅ Lint frontend
      - name: Lint frontend
        working-directory: ./frontend
        run: npm run lint

