name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install
      - run: npm run lint --if-present
      - run: npm test --if-present

      # Dependency Vulnerability Check
      - name: Run npm audit
        run: npm audit --production --audit-level=high || true

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install
      - run: npm run build

      # Dependency Vulnerability Check
      - name: Run npm audit
        run: npm audit --production --audit-level=high || true
 container-scan:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    # Backend Image
    - name: Build Backend Image
      run: docker build -t nycad-backend ./backend

    - name: Scan Backend with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: nycad-backend
        format: table
        exit-code: 0
        ignore-unfixed: true
        vuln-type: os,library

    # Frontend Image
    - name: Build Frontend Image
      run: docker build -t nycad-frontend ./frontend

    - name: Scan Frontend with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: nycad-frontend
        format: table
        exit-code: 0
        ignore-unfixed: true
        vuln-type: os,library


  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=NYCAD-sndx
            -Dsonar.organization=shravanychandhanaa
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
